#ARG CLI_IMAGE
#FROM ${CLI_IMAGE} as cli
FROM amazeeio/php:7.2-fpm

# We don't need the composer.lock file
# COPY composer.json composer.lock /app/
#COPY scripts /app/scripts


# Installing composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#COPY blog2 /var/www/html
COPY blog2 /app
#COPY composer.json /var/www/html
COPY composer.json /app
#COPY scripts /var/www/html/scripts

#RUN ln -s /app /application

#RUN apt-get update
#RUN apt-cache search zlib
#RUN apt-get install -y git zlib1g zlib1g-dev libzip-dev

# Installing PHP dependencies
RUN docker-php-ext-install pcntl
#zip

# Misc
RUN rm -f /app/composer.lock
#RUN ls -al /var/www/html
#RUN rm -rf /var/www/html/vendor
RUN composer install --dev

# Define where the Drupal Root is located
ENV WEBROOT=web
